apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.12.0 (0ab07be)
  creationTimestamp: null
  labels:
    io.kompose.service: chaos-k8s
  name: chaos-k8s
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: chaos-k8s
    spec:
      containers:
      - args:
        - "-c"
        - "chmod 777 /docker_entrypoint.sh && source /docker_entrypoint.sh"
        command: 
        - /bin/bash
        env:

        - name: K8S_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace

        - name : CHAOS_NAMESPACE
          valueFrom:
            configMapKeyRef:
                name: chaos-k8s-cm
                key: CHAOS_NAMESPACE

        - name : CLUSTER_NAME
          valueFrom:
            configMapKeyRef:
                name: chaos-k8s-cm
                key: CLUSTER_NAME

        - name : CLUSTER_REGION
          valueFrom:
            configMapKeyRef:
                name: chaos-k8s-cm
                key: CLUSTER_REGION

        image: $IMAGE_NAME
        imagePullPolicy: Always
        name: chaos-k8s
        resources: {}
      restartPolicy: Always